name: Account and Key Generator

on:
  workflow_dispatch:
    inputs:
      mail:
        description: 'Choose the mail provider'
        required: true
        type: choice
        options:
          - emailfake
          - 1secmail
          - guerrillamail
          - developermail
        default: emailfake

jobs:
  generate:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Eset Generator
        run: |
          python main.py --chrome --key --email-api ${{ github.event.inputs.mail }} --skip-update-check --no-logo

      - name: Upload Generated Keys
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: eset-real-keys
          path: |
            *KEYS*
            *keys*
            output/
